#!/bin/bash

TEST_NUMBER=0

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt http://www.mimuw.edu.pl/ \n"
./testhttp cookies.txt http://www.mimuw.edu.pl/

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt https://sportowefakty.wp.pl/ \n"
./testhttp cookies.txt https://sportowefakty.wp.pl/

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt https://sportowefakty.wp.pl/ \n"
./testhttp cookies.txt https://sportowefakty.wp.pl/

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt https://wallpapershome.com/images/pages/pic_h/21486.jpg \n"
./testhttp cookies.txt https://wallpapershome.com/images/pages/pic_h/21486.jpg

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt http://wallpapershome.com:80/images/pages/pic_h/21486.jpg \n"
./testhttp cookies.txt http://wallpapershome.com:80/images/pages/pic_h/21486.jpg

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt https://www.mimuw.edu.pl/ \n"
./testhttp cookies.txt https://www.mimuw.edu.pl/

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt https://www.mimuw.edu.pl:443/ \n"
./testhttp cookies.txt https://www.mimuw.edu.pl/

((TEST_NUMBER++))

echo -e "\n\n\n";

echo -e "Test: $TEST_NUMBER\n"
echo -e "Arguments: " "cookies.txt http://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx \n"
./testhttp cookies.txt http://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx
