#!/bin/bash

# Author: Jan Klinkosz, id number: 394 342

# $1 - path to file with cookies to send
# $2 - http address from which we want to get resource

# script to run testhttp_raw via stunnel
# this script assumes that there is testhttp_raw executable file in the same folder
# as the script (i.e. accessible in this way: ./testhttp_raw)

HTTP_PREF="http://"
HTTPS_PREF="https://"

SCRIPT_LOCATION=$(dirname $0)

# check input

if [[ ! -f $1 ]]; then
	echo "$1 is not a file"
	exit 1
fi

# variable to store conf file name
TEMP=""
TUNNEL_PID_FILE_NAM="";

clean_up () {
	if [[ -f $TEMP ]]; then
		rm -f $TEMP
	fi

	TUNNEL_PID=$(cat $TUNNEL_PID_FILE_NAME)

	kill $TUNNEL_PID

	# in a normal situation there is no need to delete
	# this file, because killing tunnel process does it for us
	if [[ -f $TUNNEL_PID_FILE_NAME ]]; then
		rm -f $TUNNEL_PID_FILE_NAME
	fi

	exit $1
}

trap clean_up SIGTERM SIGINT SIGQUIT SIGHUP

if [[ $2 = $HTTP_PREF* ]]; then
	ADDRESS=$(awk -F/ '{print $3}' <<<$2)
	if [[ $ADDRESS = *":"[0-9]* ]]; then
		valgrind --leak-check=full $SCRIPT_LOCATION/testhttp_raw $ADDRESS $1 $2
	else
		valgrind --leak-check=full $SCRIPT_LOCATION/testhttp_raw "$ADDRESS:80" $1 $2
	fi
elif [[ $2 = $HTTPS_PREF* ]]; then
	TEMP=$(mktemp -p $SCRIPT_LOCATION stunnel.confXXX)
	TUNNEL_PID_FILE_NAME=$(pwd)"/$SCRIPT_LOCATION/stunnel.pid"

	LOCAL_ADDRESS_PORT="127.0.0.1:10037"

	HTTP_ADDRESS=$(awk -F/ '{print $3}' <<<$2)

	if [[ ! $HTTP_ADDRESS = *":"[0-9]* ]]; then
		HTTP_ADDRESS="$HTTP_ADDRESS:443"
	fi

	echo "pid = $TUNNEL_PID_FILE_NAME" >> $TEMP
	echo "[service]" >> $TEMP
	echo "client = yes" >> $TEMP
	echo "accept = $LOCAL_ADDRESS_PORT" >> $TEMP
	echo "connect = $HTTP_ADDRESS" >> $TEMP

	stunnel $TEMP

	valgrind --leak-check=full $SCRIPT_LOCATION/testhttp_raw $LOCAL_ADDRESS_PORT $1 $2

	clean_up 0
else
	echo "$2 doesn't start with http:// or https://"
	exit 1
fi
